### ISSUE TITLE
Add table docker_run

### ISSUE THREAD

**Issue by mingfang** [turbot/steampipe-plugin-docker#67]
Add ability to run docker container.
Currently I'm using the `exec` plugin to run docker containers, e.g.
```
select * from exec_local.exec_command where command='docker run --rm ubuntu -- uname -a'
```
A new table `docker_run` may do the same like this
```
select * from docker_run where image='ubuntu' and command='name -a`
```

**Comment by ParthaI** [comment]
Hello @mingfang, thank you for bringing up this issue. Unfortunately, Steampipe is intentionally designed for read-only operations on resources, and all Steampipe plugins adhere to this design by not performing any write operations.

Regarding your command `docker run --rm ubuntu -- uname -a`, this is an action-oriented command intended for Docker containers. Incorporating a table in Steampipe to execute such a command falls beyond the intended scope of Steampipe's table design, which is focused on querying and reading data.

As a result, this particular issue will be closed. However, if you have any needs or questions related to performing read operations on Docker containers, please don't hesitate to open a separate issue for that purpose.

Thank you for your understanding!

**Comment by mingfang** [comment]
@ParthaI 
how do you explain the `exec` plugin's ability to run commands?
https://hub.steampipe.io/plugins/turbot/exec

Using the exec plugin you can run any command, including destructive ones
```
select
  output
from
  exec_command
where
  command = 'rm -rf';
```

**Comment by ParthaI** [comment]
Hello @mingfang, This is a single plugin where we have exceptional table usage. Basically, the plugin runs a command in the local environment and shows the output of the command that ran. The command part in the where clause is string(`... where 
 command = 'rm -rf';`). This is difficult to determine between commands that perform read operations and those that execute write operations. 

Your understanding and careful use of this feature are much appreciated. Thank You!
